transform:
  outputs:
    dev:
      dataset: silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../../credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: imdb-analytics
      threads: 1
      type: bigquery
  target: dev
